import { StyleSheet } from "react-native";

export default styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 50,
    marginTop: 40,
    backgroundColor: "#fff",
  },
  extrato: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    fontSize: 16,
    fontWeight: "bold",
    borderRadius: 10,
    borderColor: "black",
    borderWidth: 1,
    marginVertical: 5,
    marginHorizontal: 1,
    backgroundColor: "#D9D9D9",
  },
  pagamento: {
    color: "red",
    paddingVertical: 12,
    paddingHorizontal: 20,
    fontSize: 16,
    fontWeight: "bold",
    borderRadius: 10,
    borderColor: "black",
    borderWidth: 1,
    marginVertical: 5,
    marginHorizontal: 1,
    backgroundColor: "#D9D9D9",
  },
  recebimento: {
    color: "green",
    paddingVertical: 12,
    paddingHorizontal: 20,
    fontSize: 16,
    fontWeight: "bold",
    borderRadius: 10,
    borderColor: "black",
    borderWidth: 1,
    marginVertical: 5,
    marginHorizontal: 1,
    backgroundColor: "#D9D9D9",
  },
});
